vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: uploads/images/products
            upload_destination: '%kernel.project_dir%/public/uploads/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        brand_logo:
            uri_prefix: uploads/images/brands
            upload_destination: '%kernel.project_dir%/public/uploads/images/brands'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        category_images:
            uri_prefix: uploads/images/categories
            upload_destination: '%kernel.project_dir%/public/uploads/images/categories'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer